### ISSUE TITLE
Is CONFIG_X86_MSR needed to mitigate X86 CPU bugs?

### ISSUE THREAD

**Issue by a13xp0p0v** [clipos/bugs#26]
Hello!

First of all, thanks for this cool project!

I'm working to introduce some of your kernel hardening recommendations
into the [kconfig-hardened-check](https://github.com/a13xp0p0v/kconfig-hardened-check) project.

I have a question about CONFIG_X86_MSR.
It provides access from the userspace to the x86 MSRs via char devices.
Does the kernel really need it for mitigating X86 CPU bugs?

Thanks!

**Comment by tsautereau-anssi** [comment]
Hi Alexander,

You're absolutely right, I'll fix that.

Thanks!

**Comment by theLOICofFRANCE** [comment]
Hi @a13xp0p0v,

> Does the kernel really need it for mitigating X86 CPU bugs?

Maybe it was related to grsecurity that added GR_MSRWRITE_MSG "denied write to CPU MSR by"?

Hi @tsautereau-anssi and @travier-anssi,

Small off-topic question (sorry), have you your kernel config file and your kernel command line parameters accessible directly by url? (I only found kernel config for [clipos v4](https://github.com/clipos-archive/clipos4_portage-overlay-clip/tree/master/sys-kernel/clip-kernel/files))

Indeed, during my test on 2018-09-26 I identified this in your kernel command line parameters:
![2018-09-26_clipos kernel command line parameters](https://user-images.githubusercontent.com/4661917/58981521-cfc22580-87d2-11e9-9797-e11cca596b53.png)

And I would like to follow your evolutions without recompiling everything :)

Thanks !

**Comment by tsautereau-anssi** [comment]
Hello @HacKurx,

> Small off-topic question (sorry), have you your kernel config file and your kernel command line parameters accessible directly by url? (I only found kernel config for [clipos v4](https://github.com/clipos-archive/clipos4_portage-overlay-clip/tree/master/sys-kernel/clip-kernel/files))

The final kernel config file is generated from our [configsets](https://github.com/clipos/src_platform_config-linux-hardware/tree/master/kernel_config) by [a script](https://github.com/clipos/src_platform_config-linux-hardware/blob/master/make-config.sh) which can either be called from e.g. the [clipos-kernel ebuild](https://github.com/clipos/src_portage_clipos/blob/master/sys-kernel/clipos-kernel/.clipos-kernel.ebuild.0) _via_ the [clipos-kernel eclass](https://github.com/clipos/src_portage_clipos/blob/master/eclass/clipos-kernel.eclass); or directly as a regular shell script.

As for the kernel's command-line parameters, it's built during the configure step of the efiboot recipe by [this script](https://github.com/clipos/products_clipos/blob/master/efiboot/configure.d/95_dracut.sh).

> And I would like to follow your evolutions without recompiling everything :)

Be careful with "partially synchronizing" with us as it could lead to strange bugs due to inconsistencies ;)
